runtime: python27
api_version: 1
threadsafe: yes
handlers:

- url: .*
  script: main.app

- url: /assets
  static_dir: assets

- url: /dist
  static_dir: dist

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest